### ISSUE TITLE
Tracking bandwidth using Javascript Tracker

### ISSUE THREAD

**Issue by gomezhyuuga** [piwik/plugin-Bandwidth#14]
Hi there, I'm trying to use this plugin but it doesn't show anything in the pages report. I'm using the basic tracking code with javascript. Do I need to setup something in order to work? Like sending manually the bandwidth from JS?

Thanks :)

**Comment by mattab** [comment]
This plugin currently works automatically when importing server logs into Piwik:

But you could also set the `bw_bytes` value manually in JavaScript using `_paq.push(['appendToTrackingUrl', 'bw_bytes=1234');` to track the bandwidth of your pages.

**Comment by sgiehl** [comment]
As this question might come up to other people as well, I'll propose a PR to add this to the FAQ

**Comment by gomezhyuuga** [comment]
Thanks a lot 👍
