### ISSUE TITLE
Bandwidth plugin causes PHP out of memory error on reports

### ISSUE THREAD

**Issue by twpol** [piwik/plugin-Bandwidth#2]
I installed this plugin two days ago and yesterday got the first data from this plugin - all good - but today, whenever I try and view a report that includes bandwidth data I get the following error in the log:

```
Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 71 bytes) in /var/www/hosts/stats/core/DataTable.php on line 1159
```

Now obviously I can just go and increase the PHP memory limit in php.ini, but I wanted to bring this to your attention as it may be a bug in the plugin or it may be that the memory limit issue should be communicated to uses of the plugin.

**Comment by twpol** [comment]
To confirm, raising the default PHP memory_limit from 128M to 256M allows the reports to work for now.

**Comment by tsteur** [comment]
Closing it as it is normal that it consumes more memory and `128M` is not that much.
