### ISSUE TITLE
Bandwidth plugin breaks historial graphs for certain reports

### ISSUE THREAD

**Issue by twpol** [piwik/plugin-Bandwidth#3]
If I create a report with the default options, select a display options to show graphs for everything *and* select "Show Historical Graphs for the top 5 values" *and* select a report that includes bandwidth then the report generation fails with:

```
PHP Fatal error:  Call to undefined method Piwik\\DataTable\\Map::getMetadata() in /var/www/hosts/stats/plugins/Bandwidth/Bandwidth.php on line 117
```

I'm also seeing the following closely related message in the Email Reports UI but I'm not sure exactly what triggers it (it only appears sometimes):

```
WARNING Bandwidth[2015-03-02 09:29:09] [e44f3] /var/www/hosts/stats/plugins/Bandwidth/Bandwidth.php(115): Recoverable Error - Argument 1 passed to Piwik\Plugins\Bandwidth\Bandwidth::enrichApi() must be an instance of Piwik\DataTable, instance of Piwik\DataTable\Map given - Piwik 2.11.1 - Please report this message in the Piwik forums: http://forum.piwik.org (please do a search first as it might have been reported already) 
```

I'm running Piwik 2.11.1 and Bandwidth v0.1.0.

**Comment by tsteur** [comment]
@twpol  can you try to update `plugins/Bandwidth/Bandwidth.php` with the content of this link https://raw.githubusercontent.com/piwik/plugin-Bandwidth/3/Bandwidth.php and see if the error still occurs?

I could reproduce the fatal and it was gone after applying that patch. Please note the bandwidth columns might be not shown in scheduled reports, there seems to be something broken in ScheduledReports itself.

**Comment by twpol** [comment]
@tsteur Yup, that solves the fatal. Thanks!

**Comment by tsteur** [comment]
Sweet, thx for the feedback
