### ISSUE TITLE
Bandwidth sum returns negative for large byte values

### ISSUE THREAD

**Issue by mattjuna** [piwik/plugin-Bandwidth#4]
The bandwidth sum returns negative for large byte values Bandwidth/Columns/MetricsBase.php when the sum of the bytes is a large number. Commenting the cast fixes the problem.

Happens when the summary bandwidth is over 4GB 

    public function getMetricAsIntSafe(Row $row, $metric)
    {
        $value = $this->getMetric($row, $metric);

        if (false !== $value) {
            //$value = (int) $value;
        }

        return $value;
    }

**Comment by MrGeneration** [comment]
I could reproduce this on my System:
Windows Server 2008R2 x64, Apache 2.4 & PHP 5.5.26
Piwik is currentely at version 2.14.2

**Comment by tsteur** [comment]
I know this is a bit late but it will be fixed with Piwik 3 which will be released before the end of the year. Thanks for the report and the proposed fix 👍
