### ISSUE TITLE
Bandwidth.php(115): Recoverable Error

### ISSUE THREAD

**Issue by elgrafico** [piwik/plugin-Bandwidth#5]
*WARNING: /path/to/piwik/plugins/Bandwidth/Bandwidth.php(115): Recoverable Error - Argument 1 passed to Piwik\Plugins\Bandwidth\Bandwidth::enrichApi() must be an instance of Piwik\DataTable, instance of Piwik\DataTable\Map given - Piwik 2.13.1*

Occured in "Pages"
https://piwik.example.org/index.php?module=CoreHome&action=index&date=2015-02-21&period=week&idSite=47&activated=#/module=Actions&action=menuGetPageUrls&date=2015-02-21&period=week&idSite=47

Side-effect: no bandwidth columns in "Pages" (cmp. https://github.com/piwik/plugin-Bandwidth/blob/master/screenshots/Pageviews.png), whereas bandwidth is in fact displayed in "Visitor Overview"

...nice and useful plugin btw., thanks a lot!

**Comment by tsteur** [comment]
@elgrafico can you try to update `plugins/Bandwidth/Bandwidth.php` with the content of this link https://raw.githubusercontent.com/piwik/plugin-Bandwidth/3/Bandwidth.php and see if error still occurs?

I couldn't reproduce that issue.

**Comment by elgrafico** [comment]
@tsteur updated, checked, works. Thanks for the patch!
